version: '3'
services:

  #SQL Database
  postgres:
    container_name: "travelPlannerDB"
    image: "postgres"
    restart: "always"
    environment:
      POSTGRES_DB: "travel_planner_db"
      POSTGRES_USER: "viktor"
      POSTGRES_PASSWORD: "longPass"
    ports:
      - "5432:5432"

volumes:
  party-data: